### ISSUE TITLE
Call disconnects immediately after making a call - iOS.

### ISSUE THREAD

**Issue by bluedomain-online** [twilio/voice-quickstart-ios#451]
### Description
The outgoing call is getting disconnected immediately after making the call. When I make a call from my VoIP app, It's reporting the call successfully but disconnects at the very next moment. It's not a VoIP app to phone number calling but a VoIP app to VoIP app call.(Both my testing devices are successfully registered in Twilio)

#### Logs

2021-04-13 16:24:15.102120+0530 AppName[56955:17701789] [tcp] tcp_input [C46.1:3] flags=[R] seq=3567195054, ack=0, win=0 state=LAST_ACK rcv_nxt=3567195054, snd_una=2421274803
2021-04-13 16:24:15.102365+0530 `AppName`[56955:17701789] [tcp] tcp_input [C46.1:3] flags=[R] seq=3567195054, ack=0, win=0 state=CLOSED rcv_nxt=3567195054, snd_una=2421274803
2021-04-13 16:24:15.102445+0530 `AppName`[56955:17701789] [tcp] tcp_input [C45.1:3] flags=[R] seq=505483190, ack=0, win=0 state=LAST_ACK rcv_nxt=505483190, snd_una=808046957
2021-04-13 16:24:15.102575+0530 AppName[56955:17701789] [tcp] tcp_input [C45.1:3] flags=[R] seq=505483190, ack=0, win=0 state=CLOSED rcv_nxt=505483190, snd_una=808046957
2021-04-13 16:24:15.107398+0530 AppName[56955:17682877] provider:performStartCallAction:
2021-04-13 16:24:15.375803+0530 AppName[56955:17682877] provider:didActivateAudioSession:
2021-04-13 16:24:17.208333+0530 AppName[56955:17682877] callDidConnect:
2021-04-13 16:24:17.208496+0530 AppName[56955:17682877] performVoiceCall() successful
2021-04-13 16:24:17.322333+0530 AppName[56955:17682877] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"
2021-04-13 16:24:28.420145+0530 AppName[56955:17682877] Call disconnected
2021-04-13 16:24:29.424602+0530 AppName[56955:17682877] provider:didDeactivateAudioSession:

#### Voice iOS SDK

 pod 'TwilioVoice', ‘~> 5.5.2’

#### Xcode
12.4

#### iOS Version
14.2

#### iOS Device

iPhone SE 2020

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Thanks for reaching out. I have a feeling this is something to do with the actions in the TwiML response. Do you have a Call SID so we can take a look?

**Comment by bluedomain-online** [comment]
Hi  @bobiechen-twilio 

Please find the call SID "CA250b5ed01d2242d085fe6f6f5bf3f8b5".

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Thanks for providing the Call SID, and from the record I can see that the callee identity used in the TwiML has a `#` sign, which is not a supported character. For Programmable Voice clients, only alpha-numeric and underscore characters are supported: [API doc](https://twilio.github.io/twilio-voice-ios/docs/latest/Classes/TwilioVoice.html#//api/name/connectWithAccessToken:delegate:).

Let me know if the issue is resolved after changing the characters of the client identity.

**Comment by bluedomain-online** [comment]
I’m not using any special characters for identity. Instead I use a unique numerical value. But will check how the # symbol is getting appended.

**Comment by bluedomain-online** [comment]
@bobiechen-twilio I have cross-checked and confirmed that we are not using any # symbol in our identity string during JWT creation as well as while passing the identity for making a call.

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Thanks for the update. The `#` sign is actually in the client identity inside the <Dial><Client> verbs of the TwiML response generated from your server. Can you check and make sure the characters in the client identity meet the requirement.

**Comment by bluedomain-online** [comment]
Did you mean while creating JWT token? Please specify.

**Comment by bobiechen-twilio** [comment]
@bluedomain-online The server logic where the TwiML response is generated. Below is the TwiML response from your server endpoint:
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Dial answerOnBridge="true" callerId="+12027336642">
    <Client>#22397</Client>
  </Dial>
</Response>
```

As you can see the identity in the <Client> verb has a `#` sign, which is not an allowed character for the Programmable Voice SDK. Please check this particular part and make sure the identities meet the requirement.

**Comment by bluedomain-online** [comment]
Sure. I will let you know after checking.Thanks

**Comment by bluedomain-online** [comment]
This server-side issue got resolved but now I am getting another issue  "'To' phone number not verified
Error - 21219". I am using a custom id as an identity while registering to Twilio.  Is it possible to achieve calls without a phone number?

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Thanks for the update and glad that the server side issue has been resolved.
From the message it seems that the Push Credential SID used in the Access Token when calling `TwilioVoiceSDK.register()` is invalid. You can check out the [instructions](https://github.com/twilio/voice-quickstart-ios#bullet6) or create Push Credentials directly in the [developer console](https://www.twilio.com/console/voice/sdks/credentials).

Feel free to provide Call SIDs if you are still having trouble connecting clients.

**Comment by bluedomain-online** [comment]
@bobiechen-twilio please find the call SID CAca9ae4cb1f19a509fa0fbb31dff6a246.

Now even the logs are not getting updated in the console.

I am following the same steps to create the VoIP certificate and credential_sid but still not working.
The VoIP certificate created supports both sandbox as well as production. Can I use this certificate to create two credential SID for both production and development?

**Comment by bobiechen-twilio** [comment]
Thanks for providing the Call SID @bluedomain-online.

From the record, the call looks perfect - the TwiML response was correct, a push notification was delivery successfully to the callee client, and the fact that the we can see SDK events of this callee client indicates the application did receive the VoIP push notification and passed to the SDK via the `TwilioVoiceSDK.handleNotification()` method, however the incoming call was not answered or rejected and eventually timed out.

You might want set some debug breakpoints in case the incoming call notification (assuming the call is reported to CallKit) is not properly shown on UI.

And yes, the same Apple VoIP Service certificate can be used for both the sandbox and production environment, however we strongly recommended that application developers use different Twilio accounts to host your Push Credentials for different environments. For example you can create a subaccount and the sandbox Push Credential for your dev environment, and create another production Push Credential in your main account when the app is ready for store submission.

**Comment by bluedomain-online** [comment]
Thanks, @bobiechen-twilio.I will let you know if I still face issues.

**Comment by bluedomain-online** [comment]
@bobiechen-twilio Will Twilio SDK report the call to CallKit or we have to handle that?

**Comment by bobiechen-twilio** [comment]
The application is responsible of handling CallKit integration, including reporting the VoIP push notification as a new incoming call and the callback methods.

**Comment by bluedomain-online** [comment]
@bobiechen-twilio I am able to get the Call UI now. But when I report the call the provider is getting nil. Should I create a separate callKitProvider object for answering a call?
guard let provider = callKitProvider else {
            NSLog("CallKit provider not available")
            return
        }


Also, The call UI is disappearing immediately when accepting a call and I am unable to hear any audio after that.

**Comment by bobiechen-twilio** [comment]
- You can have one provider instance to handle all the CallKit requests.
- The system Call UI only stays if the device is locked when the incoming call is received.
- Please check out the quickstart and make sure your application is setting up and enabling the audio device at the correct timing.

**Comment by bluedomain-online** [comment]
Call UI is not staying even if the device is locked. @bobiechen-twilio

**Comment by bluedomain-online** [comment]
@bobiechen-twilio Getting error "Call is terminated because of no audio received: Call is terminated due to RTP timeout. No audio received from the caller."
Please find the Call SID CAbe86e8e10e9bb15cab91dde4062b1268

Also, I am not able to hear the audio when a call is made(Please let me know how to set the audio when making a  call as well as answering a call.)

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

It sounds like the audio device is not properly enabled and audio packets were not sent, therefore the call was terminated by the Voice service since it thought there is no audio flowing. Please check out our sample code and make sure the audio device is configured and enabled properly. Please provide SDK logs if you believe the quickstart is also having the same audio issue in your environment.

**Comment by bluedomain-online** [comment]
Hi @bobiechen-twilio ,
Sorry for the late reply.
I think TwilioVoiceSDK.audioDevice = audioDevice is the code for setting the audio. But Whenever I set this for an incoming call inside "provider(_ provider: CXProvider, perform action: CXAnswerCallAction)" method it is crashing. Please find the crash reason below.

 "Terminating app due to uncaught exception 'TVOAudioDeviceMustBeSetBeforeMediaStackSetup', reason: 'WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created call or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.'".

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Please check out the quickstart for examples to enable/disable the audio device. As the message of the exception suggests, the audio device should only be created and assigned to the SDK **once** during the lifecycle of a call. To re-create any new audio device, please make sure all calls are finished (disconnected) and destroyed.

**Comment by bluedomain-online** [comment]
Hi @bobiechen-twilio ,
 I have tried with the quickstart example and for incoming calls the audio is not connecting.Please check the attachment and call SID.
![WhatsApp Image 2021-05-06 at 1 01 54 PM](https://user-images.githubusercontent.com/67973593/117261596-f4ffb880-ae6d-11eb-86dc-ab34328168c4.jpeg)

I guess audioDevice.isEnabled is set to true in all the required places in the quickstart. If not please suggest.

CAba89193de76ae4887cdb80bf534d162d
CAe1b902e409a495ae27855bf5369ea01f

**Comment by bluedomain-online** [comment]
@bobiechen-twilio  Voice call is working perfectly now. Your constant support was very much helpful.  Will get back to you if I face any issues going forward. Thanks!

**Comment by bluedomain-online** [comment]
Hi @bobiechen-twilio ,

The call is failing(First call mostly) sometimes with an error "StartCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 7.)".
I have seen the same issue reported here and using a "userInitiatedDisconnect" flag will fix this issue. But in my case, I am referring to the latest VoiceQuickStart project and the issue still persists.

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Sorry for the inconvenience. This could be due to that a previous call failed or ended but for some reason the app did not inform CallKit that the call has ended.

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

The error code is typically caused due to the app not properly reporting to CallKit that a call has ended, either the disconnected, failed, or sometimes the app debugging session is terminated before finishing up with CallKit. This will persist even the next time the app is launched.

**Comment by bluedomain-online** [comment]
Hi @bobiechen-twilio ,
 I am using the below code to report the out going call to callKit as provide in the quickStart. I am getting the log as  "StartCallAction transaction request successful" but the delegate method(perform action: CXStartCallAction) call is not happening after this(Kind of stoping the code execution right after " NSLog("StartCallAction transaction request successful")"  line of code. )

    func performStartCallAction(uuid: UUID, handle: String) {
        guard let provider = callKitProvider else {
            NSLog("CallKit provider not available")
            return
        }
        
        let callHandle = CXHandle(type: .generic, value: handle)
        let startCallAction = CXStartCallAction(call: uuid, handle: callHandle)
        let transaction = CXTransaction(action: startCallAction)
        
        callKitCallController.request(transaction) { error in
            if let error = error {
                
                NSLog("StartCallAction transaction request failed: \(error.localizedDescription)")
                return
            }
            NSLog("StartCallAction transaction request successful")
            let callUpdate = CXCallUpdate()
            
            callUpdate.remoteHandle = callHandle
            callUpdate.supportsDTMF = true
            callUpdate.supportsHolding = true
            callUpdate.supportsGrouping = false
            callUpdate.supportsUngrouping = false
            callUpdate.hasVideo = false
            
            provider.reportCall(with: uuid, updated: callUpdate)
        }
    }

XCODE LOG:
2021-05-19 23:28:20.641528+0530 AppName[812:174678] providerDidBegin
2021-05-19 23:28:20.996290+0530 AppName[812:175035] StartCallAction transaction request successful

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Thanks for the update. I have tried the quickstart but was always able to receive the `provider:performStartCallAction:` callback, which then lead to the call to the `TwilioVoiceSDK.connect()` method. Please check the MacOS Console application and see if there is any device message indicating why CallKit did not raise the callback to your application.

**Comment by bluedomain-online** [comment]
Hi @bobiechen-twilio 

Could you please lead me to where to search the logs in the MacOS Console application?

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Have you managed to locate the device log and see if there is any system log message indicating why the CallKit request didn't come to your application delegate callback methods?

**Comment by bluedomain-online** [comment]
Hi @bobiechen-twilio ,

The incoming call is getting disconnected immediately. In the console, it shows "Busy" status. Please check the call SIDs below.
OutGoing SID/Incoming : CAfe9ee5e3639b4d72434d4242618ddff3 / CA1da06c01f23be9dc595a5ebd04c36b3b
CA55bd55b6dbd1bdb405c1201bd36ffba6 / CAe84d43923fbab55fd2dc43f9476db062
CA8c9bf363c6db314a545e774cf68fe25b / CA27ccf78c2af4b6ba284c1ce83c5e2eb5

LOG:

2021-06-07 06:27:38.695312-0400 App Name[21141:6922033] pushRegistry:didReceiveIncomingPushWithPayload:forType:completion:
2021-06-07 06:27:38.724801-0400 App Name[21141:6922033] callInviteReceived:
2021-06-07 06:27:38.726628-0400 App Name[21141:6922033] INFO:Twilio:[Platform](Thread 0x0x11624f9b0): Inside publishConnectionEvent:, event name: incoming
2021-06-07 06:27:38.727729-0400 App Name[21141:6922033] INFO:Twilio:[Platform](Thread 0x0x11624f9b0): Inside publishConnectionEvent:, event name: listen
2021-06-07 06:27:38.753964-0400 App Name[21141:6922033] Incoming call successfully reported.
2021-06-07 06:27:38.948264-0400 App Name[21141:6922033] INFO:Twilio:[Platform](Thread 0x0x11624f9b0): Inside publishConnectionEvent:, event name: cancel
2021-06-07 06:27:38.950135-0400 App Name[21141:6922033] cancelledCallInviteCanceled:error:, error: Call Cancelled
2021-06-07 06:27:38.950338-0400 App Name[21141:6922033] DEBUG:Twilio:[Platform](Thread 0x0x11624f9b0): -[TVOCallInvite dealloc]
2021-06-07 06:27:38.950381-0400 App Name[21141:6922033] DEBUG:Twilio:[Platform](Thread 0x0x11624f9b0): -[TVOCallerInfo dealloc]
2021-06-07 06:27:38.950888-0400 App Name[21141:6922682] EndCallAction transaction request successful
2021-06-07 06:27:39.953839-0400 App Name[21141:6922033] DEBUG:Twilio:[Platform](Thread 0x0x11624f9b0): -[TVOCancelledCallInvite dealloc]
2021-06-07 06:27:39.954097-0400 App Name[21141:6922033] DEBUG:Twilio:[Platform](Thread 0x0x11624f9b0): -[TVOMediaFactory dealloc]
2021-06-07 06:27:39.957868-0400 App Name[21141:6922033] provider:performEndCallAction:
2021-06-07 06:27:39.958084-0400 App Name[21141:6922033] Unknown UUID to perform end-call action with
Please help.

**Comment by bobiechen-twilio** [comment]
Hi @bluedomain-online 

Based on the SDK log, it looks like the app is trying to accept a call that has been canceled. I checked `CAfe9ee5e3639b4d72434d4242618ddff3` and found this child call seems to be reaching 3 clients (MacOS, Windows and Android) and some of them rejected the call.

Since the original issue has been resolved I am going to close this issue for now. Feel free to reach out to us if you run into any SDK specific issue in the future. For Programmable Voice issues, please use the Twilio Support resource so our technical support experts can provide timely assistance.

Cheers

**Comment by castrojr913** [comment]
The same thing I'm facing exactly how @bluedomain-online has described. I've also tried quick-voice example and call disconnects right away when call starts ringing.  Which Twilio pod version have u tried? I provided Xcode logs regarding Quick Voice example:

```
2021-06-15 14:20:12.200796-0500 AudioDeviceExample[1386:412549] StartCallAction transaction request successful
2021-06-15 14:20:12.203577-0500 AudioDeviceExample[1386:411066] provider:performStartCallAction:
2021-06-15 14:20:12.463913-0500 AudioDeviceExample[1386:411066] provider:didActivateAudioSession:
2021-06-15 14:20:13.831115-0500 AudioDeviceExample[1386:411066] callDidStartRinging:
2021-06-15 14:20:14.232909-0500 AudioDeviceExample[1386:412647] [connection] nw_resolver_start_query_timer_block_invoke [C6] Query fired: did not receive all answers in time for eventgw.twilio.com:443
2021-06-15 14:20:14.591098-0500 AudioDeviceExample[1386:411066] callDidConnect:
2021-06-15 14:20:14.865850-0500 AudioDeviceExample[1386:412554] A route change ocurred while the AudioUnit was started. Checking the active audio format.
2021-06-15 14:20:15.100418-0500 AudioDeviceExample[1386:411066] Call disconnected
2021-06-15 14:20:16.092115-0500 AudioDeviceExample[1386:411066] provider:didDeactivateAudioSession:
```
